clone/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from quora import views

urlpatterns = [
    path('',views.ques_list),
    path('admin/', admin.site.urls),
    path('quora/',include('quora.urls'),name = 'quora'),
    path('',include('django.contrib.auth.urls')),
    path('oauth/',include('social_django.urls',namespace='social')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

quora/urls.py
from django.urls import path ,include
from . import views


app_name = 'quora'

urlpatterns = [
    path('home/',views.ques_list,name = 'ques_list'),
    path('ques/<int:id>/',views.ques_detail,name='ques_detail'),
    path('login/',views.user_login,name = 'user_login'),
    path('logout/',views.user_logout ,name = 'user_logout'),
    path('register/',views.register,name = 'register'),
    path('edit_profile/',views.edit_profile , name = 'edit_profile'),
    path('ask_question/',views.ask_question,name = 'ask_question'),
    path('update_ques/<int:id>/',views.update_ques ,name = 'update_ques'),
    path('delete_ques/<int:id>/', views.delete_ques, name='delete_ques'),
    path('likes/',views.ques_likes,name ='ques_likes'),
    path('comment_reply/<int:id>',views.comment_reply,name = 'comment_reply'),
    path('profilepage/<str:username>/',views.profilepage,name='profilepage'),
    path('delete_comment/<int:id>',views.delete_comment,name='delete_comment'),
    path('delete_reply/<int:id>', views.delete_reply, name='delete_reply'),
    path('ques_fav/',views.ques_fav,name='ques_fav'),
    path('show_fav_ques/',views.show_fav_ques,name='show_fav_ques'),
]

quora/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):

    STATUS_CHOICES = (
        ('draft' , 'Draft'),
        ('published' , 'Published')
    )

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120)
    author = models.ForeignKey(User , related_name='blog_posts' , on_delete=models.CASCADE)
    body = models.TextField()
    likes = models.ManyToManyField(User , related_name='post_likes',blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10 , choices=STATUS_CHOICES,default='draft')
    restrict_comments = models.BooleanField(default=False)
    favourite_ques = models.ManyToManyField(User,related_name='favourite_ques',blank=True)

    def __str__(self):
        return self.title



class Profile(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    DOB = models.DateField(null=True,blank=True)
    photo = models.ImageField(null=True,blank=True)

    def __str__(self):
        return "profile {}".format(self.user.username)



class Comment(models.Model):

    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_comment')
    ques = models.ForeignKey(Question,on_delete=models.CASCADE,related_name='ques_comment')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}-{}'.format(self.ques.title , self.user.username)



class Replies(models.Model):

    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_reply')
    comment = models.ForeignKey(Comment , on_delete=models.CASCADE,related_name='comment_reply')
    ques = models.ForeignKey(Question,on_delete=models.CASCADE,related_name='ques_reply')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}-{}-{}'.format(self.comment.id,self.ques.title,self.user.username)

quora/forms.py
from django import forms
from .models import Question , Profile , Comment , Replies
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(label = "Password" , widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email'
                  ,'password','confirm_password']

    def clean_confirm_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Password Mismatch')
        else:
            return confirm_password


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['DOB','photo']


class QuestionAskForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title' , 'body' ,'status','restrict_comments']


class QuesUpdateForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title','body','status','restrict_comments']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

quora/views.py
from django.shortcuts import render , get_object_or_404 , Http404
from .models import Question , Profile , Comment , Replies
from .forms import (LoginForm ,
                    QuestionAskForm ,
                    UserRegistrationForm ,
                    ProfileUpdateForm ,
                    UserUpdateForm ,
                    QuesUpdateForm,
                    CommentForm,
                    )
from django.contrib.auth import authenticate ,logout ,login
from django.http import HttpResponse , HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User

def ques_list(request):

    ques = Question.objects.all().order_by('-id')
    context = {
        'ques' : ques
    }

    return render(request , 'quora/ques_list.html' , context = context)



def ques_detail(request,id):

    ques = get_object_or_404(Question,id=id)

    replies = Replies.objects.all().filter(ques = ques).order_by('-id')

    is_liked = False
    if ques.likes.filter(id = request.user.id).exists():
        is_liked = True

    is_favourite = False
    if ques.favourite_ques.filter(id=request.user.id).exists():
        is_favourite = True

    comments =  Comment.objects.all().filter(ques = ques).order_by('-id')

    if request.method == 'POST':

        if ques.restrict_comments:
            messages.success('Commenting on this post is restricted')
            return HttpResponseRedirect(reverse('quora:ques_detail',args = (id,)))

        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('quora:user_login'))

        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            cmnt = comment_form.save(commit=False)
            cmnt.user = request.user
            cmnt.ques = ques
            cmnt.save()
            return HttpResponseRedirect(reverse('quora:ques_detail',args = (id,)))
    else:
        comment_form  = CommentForm()

    context = {
        'q': ques,
        'is_liked' : is_liked,
        'is_favourite' : is_favourite,
        'likes_count' : ques.likes.count() ,
        'comments' : comments,
        'comment_form' : comment_form ,
        'replies' : replies,
    }

    return render(request, 'quora/ques_detail.html', context=context)



def ques_likes(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('quora:user_login'))

    ques = get_object_or_404(Question,id = request.POST.get('q_id'))

    if ques.likes.filter(id = request.user.id).exists():
        ques.likes.remove(request.user)
    else:
        ques.likes.add(request.user)

    return HttpResponseRedirect(reverse('quora:ques_detail',args=(request.POST.get('q_id'),)))



def ques_fav(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('quora:user_login'))

    ques = get_object_or_404(Question,id = request.POST.get('q_id'))

    if ques.favourite_ques.filter(id = request.user.id).exists():
        ques.favourite_ques.remove(request.user)
    else:
        ques.favourite_ques.add(request.user)

    return HttpResponseRedirect(reverse('quora:ques_detail',args=(request.POST.get('q_id'),)))



def show_fav_ques(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('quora:user_login'))

    questions = request.user.favourite_ques.all().order_by('-id')
    context = {
        'questions' : questions,
    }
    return render(request,'quora/favourites.html',context)

def comment_reply(request,id):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('quora:user_login'))

    text = request.POST.get('text')

    if len(text)==0:
        messages.success(request,'TextField is empty')
        return HttpResponseRedirect(reverse('quora:ques_detail', args=(id,)))

    ques = get_object_or_404(Question, id=id)

    comment_id = request.POST.get('comment_id')
    comment = Comment.objects.filter(id=comment_id).first()
    Replies.objects.create(ques = ques,comment=comment,user = request.user,content =text)

    return HttpResponseRedirect(reverse('quora:ques_detail',args=(id,)))



def user_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('quora:ques_list'))

    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username,password=password)

            if user:

                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('quora:ques_list'))
                else:
                    return HttpResponse('User is not Active')
            else:
                return HttpResponse('User Not Available')
    else:
        form = LoginForm()

    context = {
        'form' : form
    }

    return render(request ,'quora/login.html' ,context )



@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('quora:ques_list'))



def register(request):

    if request.user.is_authenticated:
        return HttpResponse('First logout')

    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Profile.objects.create(user = user)
            return HttpResponseRedirect(reverse('quora:user_login'))
    else:
        form = UserRegistrationForm()

    context = {
        'form' : form
    }

    return render(request , 'quora/register.html',context)



def edit_profile(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('quora:user_login'))

    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST , instance=request.user )
        profile_form = ProfileUpdateForm(request.POST ,
                            instance=request.user.profile,files =request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

        return HttpResponseRedirect(reverse('quora:profilepage',args=(request.user.username,)))

    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'user_form' : user_form,
        'profile_form' : profile_form,
    }

    return render(request,'quora/edit_profile.html',context)



def profilepage(request,username):
    user = User.objects.get(username=username)
    questions = Question.objects.filter(author=user)
    profile = Profile.objects.all()
    context = {
        'questions': questions,
        'profile' : profile,
        'user':user,
    }

    return render(request,'quora/profilepage.html',context)



@login_required()
def ask_question(request):

    if request.method == 'POST':
        form = QuestionAskForm(request.POST)

        if form.is_valid():
            ques = form.save(commit=False)
            ques.author = request.user
            ques.save()

            return HttpResponseRedirect(reverse('quora:ques_list'))
    else:
        form = QuestionAskForm()

    context = {
        'form' : form
    }

    return render(request , 'quora/ask_question.html',context)



@login_required()
def update_ques(request,id):

    ques = get_object_or_404(Question,id=id)
    print(ques.author)

    if ques.author != request.user:
        return Http404()

    if request.method == 'POST':
        form = QuesUpdateForm(request.POST,instance=ques)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('quora:ques_detail',args=(id,)))
    else:
        form = QuesUpdateForm(instance=ques)

    context = {
        'form' : form ,
        'ques' : ques ,
    }

    return render(request ,'quora/update_ques.html',context)



def delete_ques(request,id):

    ques = get_object_or_404(Question,id=id)

    if ques.author != request.user:
        return Http404()

    if request.method =='POST':
        ques.delete()
        return HttpResponseRedirect(reverse('quora:ques_list'))

    context = {
        'ques' : ques
    }



def delete_comment(request,id):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('quora:user_login'))

    cmnt_id = request.POST.get('comment_id')
    cmnt = get_object_or_404(Comment,id=cmnt_id)

    if cmnt.user != request.user:
        return Http404()
    cmnt.delete()
    return HttpResponseRedirect(reverse('quora:ques_detail', args=(id,)))



def delete_reply(request, id):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('quora:user_login'))

    reply_id = request.POST.get('reply_id')
    reply = get_object_or_404(Replies, id=reply_id)

    if reply.user != request.user:
        return Http404()
    reply.delete()
    return HttpResponseRedirect(reverse('quora:ques_detail', args=(id,)))

templates/quora/ask_question.html
{% extends 'quora/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<h1 class="display-5">Ask a Question!</h1>
	<hr class="my-4">
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" name="submit" class="btn btn-success mb-2" value="Ask">
		<input type="reset" name="reset" class="btn btn-secondary mb-2" value="Reset">
	</form>

{% endblock %}

templates/quora/base.html
{% load static %}
{% load tags %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
	<link rel="stylesheet" href="{% static 'styles/app.css' %}" type="text/css" />
	<title>
		Grequo
	</title>
</head>
<body>
	<nav class="navbar navbar-dark navbar-expand-md fixed-top">
		<a class="navbar-brand" href="/">Grequo</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbar1">
		  <ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'quora:ques_list' %}"><i class="fas fa-home"></i> Home</a>
			</li>
			{% if request.user.is_authenticated %}
				<li class="nav-item"><a class="nav-link" href="{% url 'quora:ask_question' %}"><i class="fas fa-edit"></i> New Question</a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'quora:show_fav_ques' %}"><i class="fas fa-star"></i> Favourites</a></li>
			{% endif %}
		  </ul>
		  {% if request.user.is_authenticated %}
				<ul class="nav navbar-nav navbar-right">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'quora:profilepage' username=user.username %}">
							{% if request.user.profile.photo %}
								<img src="{{ request.user.profile.photo.url }}" width="23" height="23" class="d-inline-block align-top" alt="profilePic">
							{% else %}
								<img src="/media/default.png" width="23" height="23" class="d-inline-block align-top" alt="profilePic">
							{% endif %}
							{{ request.user }}
						</a>
					</li>
					<li class="nav-item"><a class="nav-link" href="{% url 'quora:user_logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a></li>
				</ul>
				{% else %}
					<ul class="nav navbar-nav navbar-right">
						<li class="nav-item"><a class="nav-link" href="{% url 'quora:user_login' %}"><i class="fas fa-sign-in-alt"></i> Login</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'quora:register' %}"><i class="fas fa-user-plus"></i> Register</a></li>
					</ul
				{% endif %}
		</div>
	</nav>
	<div class="jumbotron jumbotron-fluid">
		<div class="container container-fluid">
			{% block content %}
			{% endblock %}
		</div>
	</div>
	<footer class="footer">
		<p>A Platform for EV Enthusiasts</p>
		<a href="contact_us.html"> Contact Us</a>
	</footer>
	<script type="module" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"></script>
	<script nomodule="" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"></script>
	<script src="{% static 'scripts/app.js' %}"></script> 
</body>
</html>

templates/quora/delete_ques.html
<h2>Are you sure you want to delete {{ques.title}}</h2>
<p>
	<a href="{% url 'quora:ques_detail'  ques.id %}">Cancel</a>
</p>
<form method="POST">
	{% csrf_token %}
	<input type="submit" name="submit" value="Delete">
</form>

templates/quora/login.html
{% extends 'quora/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<h1 class="display-5">Log In!</h1>
	<hr class="my-4">
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		<input type="submit" class="btn btn-primary mb-2" name="submit" , value='Login'>
	</form>
	<br>
	<a class="align-middle" href="{% url 'password_reset' %}">Forgotten Your password?</a><br>
	<h5 class="align-middle">OR</h5>
	<a class="align-middle" href="{% url 'quora:register' %}">Create a new account!</a>
	<div>
		<h3>Login with :</h3>
		<a href="{% url 'social:begin' 'google-oauth2' %}">
			<button type="button" name="button" class="btn btn-danger">Google</button>
		</a>
	</div>

{% endblock %}

templates/quora/ques_detail.html
{% extends 'quora/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load tags %}
{% load tags%}
{% block content %}

<!-- {% block title %}{{q.title}}|{{block.super}}{% endblock %} -->
<!-- Button trigger modal -->
  
<!-- Modal -->
<div>
	<h2 class="display-6">Question Details</h2>
	<hr class="my-4">
	<div>
		<h2><p>Title: {{q.title}}</p></h2>
		<p><strong>Author: </strong><a href="{% url 'quora:profilepage' q.author %}">{{q.author}}</a>
		<span class="float-right">
			<span style="text-transform: capitalize;" class="badge badge-secondary">{{q.status}}</span>
		</span></p>
		<h4>Description:</h4><h6>{{q.body}}</h6>
	</div>
	<hr class="my-4">
	<div class="reaction">
		<form action="{% url 'quora:ques_likes' %}" method="POST">
			{% csrf_token %}
			{% if is_liked %}
				<button class="btn btn-danger" type="submit" name="q_id" value="{{ q.id }}"><i class="fas fa-thumbs-up"></i> Dislike <span class="badge badge-light">{{ likes_count }}</span></button>
			{% else %}
				<button class="btn btn-outline-danger" type="submit" name="q_id" value="{{ q.id }}"><i class="fa fa-thumbs-up"></i> Like <span class="badge badge-light">{{ likes_count }}</span></button>
			{% endif %}
		</form>
		<form action="{% url 'quora:ques_fav' %}" method="POST">
			{% csrf_token %}
			{% if is_favourite %}
				<button class="btn btn-warning" type="submit" name="q_id" value="{{ q.id }}"><i class="fas fa-star"></i> Remove from Favourites</button>
			{% else %}
				<button class="btn btn-outline-warning" type="submit" name="q_id" value="{{ q.id }}"><i class="fa fa-star"></i> Add to Favourites</button>
			{% endif %}
		</form>
	</div>

	<div class="reaction2">
		{% if request.user == q.author %}
			<a class="btn btn-outline-warning mb-2" href="{% url 'quora:update_ques' q.id %}"><i class="fas fa-edit"></i> Edit</a>
			<!-- <br> -->
			<button type="button" class="btn btn btn-outline-danger mb-2" data-toggle="modal" data-target="#exampleModalCenter">
				<i class="fas fa-trash"></i> Delete
			</button>
			<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
				<div class="modal-dialog modal-dialog-centered" role="document">
					<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLongTitle">Delete Question?</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-body">
						Are you sure you want to delete this Question?
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary mb-2" data-dismiss="modal">Close</button>
						<form method="POST" action="{% url 'quora:delete_ques' q.id %}">
							{% csrf_token %}
							<input class="btn btn-danger mb-2" type="submit" name="submit" value="Delete">
						</form>
					</div>
					</div>
				</div>
			</div>
			<!-- <a class="btn btn-outline-danger mb-2" href="{% url 'quora:delete_ques' q.id %}"><i class="fas fa-trash"></i> Delete</a> -->
		{% endif %}
	</div>
</div>
<hr class="my-4">
	{% if not q.restrict_comments %}
		<h4>{{ comments.count}} Reply</h4>
		<hr class="my-4">
			{% for comment in comments %}
			<div class="media">
				<img style="background-color: inherit;" class="mr-3" height="30" width="30" src="{% static 'comments.png' %}" alt="Generic placeholder image">
				<div class="media-body">
					<h5 class="mt-0">
						<p><strong>@</strong><a href="{% url 'quora:profilepage' comment.user %}">{{comment.user}}</a>
							<span class="float-right">{{comment.timestamp}}</span>
						</p>
					</h5>
					<p>
						{{ comment.content }}
						{% if request.user == comment.user %}
							<form action="{% url 'quora:delete_comment' q.id %}" method="POST">
								{% csrf_token %}
								<button class="btn btn-outline-danger btn-sm" type="submit" name="comment_id" value="{{comment.id}}"><i class="fas fa-trash"></i> Delete</button>
							</form>
						{% endif %}
					</p>
					<br>
					<h4>{{ replies|count_reply:comment}} Replies</h4>
					{% for reply in replies|in_category:comment %}
						<div class="media mt-3">
							<p class="pr-3" href="#">
								<img style="background-color: inherit;" src="{% static 'comments.png' %}" height="30" width="30" alt="Generic placeholder image">
							</p>
							
							<div class="media-body">
								<h5 class="mt-0">
									<p><strong>@</strong><a href="{% url 'quora:profilepage' reply.user %}">{{reply.user}}</a>
										<span class="float-right">{{comment.timestamp}}</span>
									</p>
								</h5>
								<p>{{ reply.content }}</p>
								<br>
								{% if request.user == reply.user %}
									<form action="{% url 'quora:delete_reply' q.id %}" method="POST">
									{% csrf_token %}
										<button class="btn btn-outline-danger btn-sm" type="submit" name="reply_id" value="{{reply.id}}"><i class="fas fa-trash"></i> Delete</button>
									</form>
								{% endif %}
							</div>
						</div>
					{% endfor %}
					<br>
					<form class="form-inline" method="POST" action="{% url 'quora:comment_reply' q.id %}">
						{% csrf_token %}
						<div class="form-group mx-sm-3 mb-2">
							<input class="form-control" type="text" placeholder="Reply!" name="text" value="">
						</div>
						<button class="btn btn-outline-primary mb-2" type="submit" name="comment_id" value="{{comment.id}}"><i class="fas fa-comment"></i> Reply</button>
					</form>
					<br>
				</div>
			</div>
			{% endfor %} 
		<h4>Answer here: </h4>
		<form method="POST">
			{% csrf_token %}
			{{ comment_form|crispy }}
			<button class="btn btn-outline-primary" type="submit" name="comment_id" value="{{comment.id}}"><i class="fas fa-comment"></i> Comment</button>
		</form>
		<br><br>
	{% else %}
	<div class="alert alert-danger" role="alert">
		<h6><i class="fas fa-comment-slash"></i> Comments on this post are restricted!</h6>
	</div>
	{% endif %}

{% endblock %}

templates/quora/reply.html
{% extends 'quora/ques_detail.html' %}
{% load crispy_forms_tags %}
{% block commentreply %}
	sparsh
	<h4>Reply below:</h4>
	<form method="POST" action="{% url 'quora:comment_reply' comment.id %}">
		{% csrf_token %}
		{{ reply_form|crispy }}
		<button type="submit" name="comment_id" value="{{comment.id}}"></button>
	</form>

	<br><br>
	<h4>{{ replies.count}} Replies</h4>
	<div>
		{% for reply in replies %}
			<p>{{ reply.content }}</p>
			<pre>by-{{reply.user}}        -- {{reply.timestamp}}</pre>
		{% endfor %}
	</div>

{% endblock %}